---
title: "Intro to data visualization"
author: "Zhe"
format: html
---

## Set up
```{r}
#| message: false
#| warning: false

library(readr)
library(dplyr)
library(tidyr)
library(forcats) # makes working with factors easier
library(ggplot2)
library(leaflet) # interactive maps
library(DT) # interactive tables
library(scales) # scale functions for visualization
library(janitor) # expedite cleaning and exploring data
library(viridis) # colorblind friendly color palette
```
## Read data
```{r}
#| message: false
#| warning: false
elta_visits_raw <- read_csv("https://portal.edirepository.org/nis/dataviewer?packageid=edi.587.1&entityid=cda8c1384af0089b506d51ad8507641f")
```
## Data Exploration
```{r}
#| eval: false
colnames(elta_visits_raw)
glimpse(elta_visits_raw)
unique(elta_visits_raw$Date)
```
## Getting data ready for visulization

```{r}
delta_visits <- elta_visits_raw %>% 
  janitor::clean_names()
colnames(delta_visits)
```

## Transforming data from wide to long
```{r}
visits_long <- delta_visits %>% 
  pivot_longer(cols = c(sm_boat, med_boat, lrg_boat, bank_angler, scientist, cars),
               names_to = "visitor_type",
               values_to = "quantity") %>% 
  rename(restore_loc = EcoRestore_approximate_location) %>% 
  select(-notes)
```


## Calculate the daily visits to long?
```{r}
daily_visits_loc <- visits_long %>%
    group_by(restore_loc, Date, visitor_type) %>% 
    summarise(daily_visits = sum(quantity))
    
head(daily_visits_loc)
```

## Plotting with ggplot
```{r}
ggplot(data = daily_visits_loc,
       aes(x = restore_loc, y = daily_visits))+
    geom_col()

```

## Customizing our plot
```{r}
ggplot(daily_visits_loc,
    aes(x = restore_loc,
         y = daily_visits,
         fill = "blue"))+
 geom_col()
         
```

```{r}
ggplot(daily_visits_loc,
    aes(x = restore_loc,
         y = daily_visits,
         fill = visitor_type))+
 geom_col()
```

- use the 'labs()' to modify labels
- flip x and y axis
- modify 
```{r}
ggplot(data = daily_visits_loc,
       aes(x = restore_loc, y = daily_visits,
           fill = visitor_type))+
    geom_col()+
    labs(x = "Restoration Location",
         y = "Number of Visits",
         fill = "Type of Visitor",
         title = "Total Number of Visits to Delta Restoration Areas by visitor type",
         subtitle = "Sum of all visits during July 2017 and March 2018")+
    coord_flip()+
    theme_bw()+
theme(legend.position = "bottom",
      axis.ticks.y = element_blank())
scale_y_continuous(breaks = seq(0,120, 20), expand = c(0,0))

```


```{r}
daily_visits_total <- daily_visits_loc %>% 
  group_by(restore_loc) %>% 
  mutate(n = sum(daily_visits)) %>% 
  ungroup()
```


```{r}
ggplot(data = daily_visits_total,
       aes(x = restore_loc, y = daily_visits,
           fill = visitor_type))+
    geom_col()+
    labs(x = "Restoration Location",
         y = "Number of Visits",
         fill = "Type of Visitor",
         title = "Total Number of Visits to Delta Restoration Areas by visitor type",
         subtitle = "Sum of all visits during July 2017 and March 2018")+
    coord_flip()+
    theme_bw()+
    theme(legend.position = "bottom",
      axis.ticks.y = element_blank())+
    scale_fill_viridis_d()
```
## saving plot
```{r}
ggsave("../plots/visit_restore_site_delta.jpg", width = 12, height = 6, units = "in")
```


